### ISSUE TITLE
Why does it require such a large amount of memory？

### ISSUE THREAD

**Issue by Nineteeninetynine** [Kunhao-Liu/StyleGaussian#11]
RuntimeError: CUDA out of memory. Tried to allocate 130674.91 GiB (GPU 0; 79.15 GiB total capacity; 27.53 GiB already allocated; 37.61 GiB free; 28.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Feature training:   0%|| 0/30000 [00:00<?, ?it/s]     running train_feature.py

**Comment by gwilczynski95** [comment]
Hey! Did you solve the problem in any way? Sorry, just seen your PR, I'm going to look into it
