### ISSUE TITLE
Question for Wikiart datasets

### ISSUE THREAD

**Issue by SCUTykLin** [Kunhao-Liu/StyleGaussian#2]
I note that the wikiart datasets have 37GB, Did u use the all style images for training? If not, can u provide the partial dataset which u use?

**Comment by Kunhao-Liu** [comment]
Hi, we train on all style images without splitting the dataset. In each iteration, we randomly select a style image from the dataset.

**Comment by YingjianYu** [comment]
Thank you for your excellent work! Could you please offer your download link of the Wikiart datasets?

**Comment by Kunhao-Liu** [comment]
Hi, you can download the dataset from this link: https://www.kaggle.com/datasets/ipythonx/wikiart-gangogh-creating-art-gan
