### ISSUE TITLE
isseus on reproduction

### ISSUE THREAD

**Issue by sHaol0w** [Kunhao-Liu/StyleGaussian#4]
Hi, I have tried to produce the results in your paper, but..
<img width="1425" alt="1712819937610" src="https://github.com/Kunhao-Liu/StyleGaussian/assets/16890591/8f653428-960c-4aad-b166-476c27ff52eb">

is this right?
I exactly follows the instructions

**Comment by sHaol0w** [comment]
Oh! Maybe because I used a 26G wikiart dataset. I am trying the 36G version

**Comment by Kunhao-Liu** [comment]
Hi, how are your results on the 36G dataset version? We expect some randomness in the results, so they might not perfectly match what's shown in the paper.

**Comment by sHaol0w** [comment]
It works just like shown in the paper! Appreciate your contribution in this field.
It may be more stable than your expectation, hhhhhhh
<img width="1003" alt="1714116543805" src="https://github.com/Kunhao-Liu/StyleGaussian/assets/16890591/95f1896d-e86c-47bb-b56a-61c929d878f1">

**Comment by Kunhao-Liu** [comment]
Oh! Glad to know that. Thank you!

**Comment by sHaol0w** [comment]
Oh, Sorry, I messed up the results... I'm doing something else these days ...
These are the reproduction results. They differ a little from your paper and checkpoints (these two align well)
I guess, do you use a decoder checkpoint trained on multiple (means many, not one or two or three) scenes? (As you mentioned in paper and READEME, the initialization)
<img width="1430" alt="1714145703792" src="https://github.com/Kunhao-Liu/StyleGaussian/assets/16890591/b368134d-ec89-4b04-8b6f-48f9a7582e0b">

**Comment by Kunhao-Liu** [comment]
I trained the decoder on only one scene... I guess the difference is mainly due to training. I use a batch size of 1, and the training style images are chosen randomly, which may make the training results unstable.
