### ISSUE TITLE
Request for more datasets.

### ISSUE THREAD

**Issue by Kim-GeonU** [Kunhao-Liu/StyleGaussian#6]
Great work! I really appreciate you open the source code and pre-processed datasets.

I have a request that, can you please open more pre-precessed scenes of tank&temples, for example, the Playground?

Thank you!

**Comment by Kunhao-Liu** [comment]
Hi, thank you! We have the exact same pre-process procedure of the dataset as in [3DGS](https://github.com/graphdeco-inria/gaussian-splatting). You can simply run `convert.py` to get the datasets in the same format. In all experiments we use the images downscaled with a factor of 4.

**Comment by Kim-GeonU** [comment]
Thank you for your response!

**Comment by zAuk000** [comment]
> Thank you for your response!

Hi, do you have the processed Playground dataset? I'm encountering an error when processing with COLMAP on my device, and I'm unable to run convert.py properly.

**Comment by zAuk000** [comment]
> Hi, thank you! We have the exact same pre-process procedure of the dataset as in [3DGS](https://github.com/graphdeco-inria/gaussian-splatting). You can simply run `convert.py` to get the datasets in the same format. In all experiments we use the images downscaled with a factor of 4.

Hi, Could I request a copy of the processed Playground dataset? I'm encountering an error when processing with COLMAP on my device, and I'm unable to run convert.py properly.
