### ISSUE TITLE
limitation proposed in your paper

### ISSUE THREAD

**Issue by soohyoen** [Kunhao-Liu/StyleGaussian#8]
The limitation of your paper states that the number of gaussians is limited to 3 x 10^5.
But I don't want to limit this because I want style transfer in a small scene.
Maybe if you limit the number of Gaussian, the quality of the style transfer results will be bad.
So how do I fix the code to fix this?

**Comment by Kunhao-Liu** [comment]
Hi, you can change the `max_point_num` in this line: https://github.com/Kunhao-Liu/StyleGaussian/blob/main/scene/gaussian_model.py#L502

**Comment by soohyoen** [comment]
@Kunhao-Liu Thank you for your help!!
