### ISSUE TITLE
tnt datasets for StyeleRF

### ISSUE THREAD

**Issue by SCUTykLin** [Kunhao-Liu/StyleGaussian#9]
Hello:
   I note that u compare with StyleRF on tnt datasets. Can u provide the tnt preprocess dataset? I think its NSVF format, but I use the tnt datasets from arf and it doesn't work, lack of bbox.txt file.

Thanks.

**Comment by Kunhao-Liu** [comment]
Hi we use the tnt datasets preprocessed by [NeRF++](https://github.com/Kai-46/nerfplusplus), you can download their datasets at [this link](https://drive.google.com/file/d/11KRfN91W1AxAW6lOFs4EeYDbeoQZCi87/view?usp=sharing).

**Comment by SCUTykLin** [comment]
Thanks for yout reply. But I use your tankandtemple dataset class and it told me lacks of bbox.txt.  Did I use the worse config? 
Or can u provide the tnt config? Thanks very much

**Comment by Kunhao-Liu** [comment]
hi, you should use this file instead: https://github.com/Kunhao-Liu/StyleRF/blob/360/dataLoader/tnt.py
